# Copy this file to config.py and fill in your values
TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_HERE"
YOUR_CHAT_ID = 123456789

DROP_THRESHOLD = -8
RISE_THRESHOLD = 10
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 65
FUNDAMENTAL_MIN_SCORE = 14

ALPACA_API_KEY = "YOUR_ALPACA_API_KEY_HERE"
ALPACA_SECRET = "YOUR_ALPACA_SECRET_HERE"